#!/usr/bin/env bash

############# assert dirs exist
mkdir -p $Ell/docs/_includes
mkdir -p $Ell/etc
mkdir -p $Ell/src
mkdir -p $Ell/test

docs()    { $Ell/etc/moon2md $Ell/src $Ell/docs/_includes; }
here()    { cd $1; basename `pwd`; }
aliases() {
 cd $1
 for f in *.moon; do
   if grep -qs "^#!\/usr\/bin\/env" $f; then
     chmod +x $f
     eval "alias ${f%.moon}=\"./$f\""; fi; done
}

aliases $Ell/src
aliases $Ell/test

alias ..='cd ..'
alias ...='cd ../../../'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias gp="git add *;git commit -am save;git push;git status"
alias ls="ls -G"
alias tmux="tmux -f $Ell/etc/tmux-conf "
alias vi="vim -u $Ell/etc/vimrc "
alias vims="vim +PluginInstall +qall"         

PROMPT_COMMAND='echo -ne "🌜$(git branch 2>/dev/null | grep '^*' | colrm 1 2):";PS1="$(here ..)/$(here .):\!\e[m ▶ "'

tput bold; tput setaf 241
echo "Short cuts:"
alias | sed 's/alias /  /'
tput sgr0
