#!/usr/bin/env bash

doc() { gawk '
BEGIN {print "---\ntitle: \"'$1'\"\n---\n"}
/^#!\/usr\/bin/ { next }
/^-- vim: /     { next }

last { print last }
{ if ($0 ~ /^--/) {
    if(!com) print  pre;
    pre="```\n"
    com=1 
  } else {
    if(com) print "\n```moonscript"
    com=0
  }
  sub(/^--[ ]+/,"")
  sub(/^[ \t]*$/,"")
  last = $0}
END {
  if(last) print last
  if (!com) print "```"} ' $1
}


sep=""
echo "" > $2/localtoc.html
cd $1
for f in *.moon;do
  g=${f%.moon}
  doc $f > ../docs/${g}.md
  echo  "&nbsp;&nbsp; &#9679; <a href=\"$g\">$g</a><br>" >> $2/localtoc.html
done
